### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by Hueristic** [farin/JCloisterZone#200]
1)Removed and added to new request here. https://github.com/farin/JCloisterZone/issues/214

2) Also a option to add another set of tiles (within as well as at setup) would be great if there is an especially interesting game with the board game we vote and if everyone agrees we add another tileset and continue. This would be a great in game feature and easily added I would think.

I've never asked for a feature on github and failed googling but I have noticed there are issues labeled as feature. I unfortunatley seem to be too stupid to figure out how to add that label! When i click the "!" on the open button (only one i can find besides the one on the issues button which only links me to a list of issues) I have no action, it is as if i am clicking on any non populated part of the screen,

**Comment by farin** [comment]
i don't understand 2) 
What set of tiles do you mena? Could you please explain it?

**Comment by Hueristic** [comment]
The tiles are the board pieces. And thanks for the quick response! :)

**Comment by Hueristic** [comment]
Oh, and are you the only one that can add a label?

**Comment by farin** [comment]
it's not about tiles - I don't understand sense of this paragraph - "Also a option to add another set of tiles (within as well as at setup) would be great if there is an especially interesting game with the board game we vote and if everyone agrees we add another tileset and continue. This would be a great in game feature and easily added I would think"

and yes, only I can add labels

**Comment by Hueristic** [comment]
when the tiles run out we would like the option to add another set of tiles to continue the game {maybe with a vote button added if a player suggests to continue? 

So IOW the original tileset would just get added to the current list of tiles or if chosen before the game then the tileset would be doubled or even tripled (that could be in the setup options.

Another nice addition would be for the game to save the last setup options and reload those when restarted as sometimes i forget to set the small cities check box.

**Comment by x-iso** [comment]
It doesn't really makes sense to add tile sets towards the end of game since it just throws out the window all strategy efforts. It resets the odds and more often than not in favor of one who loses and suggests adding tile sets. It makes much more sense to just start another round.

However, I just thought of something a bit different. Add ability to continue the match with selected tile sets (maybe even additional meeples and rules along with them), but make score count anyway and save results as some sort of set point. So the difference with regular rematch is that you build around existing world and also you could later see global score table (who won how much of the sets and who made most score overall, etc).
________________________________
От: Hueristic
Отправлено: 08.12.2015 19:41
Кому: farin/JCloisterZone
Тема: Re: [JCloisterZone] Feature Request (#200)

when the tiles run out we would like the option to add another set of tiles to continue the game {maybe with a vote button added if a player suggests to continue?

So IOW the original tileset would just get added to the current list of tiles or if chosen before the game then the tileset would be doubled or even tripled (that could be in the setup options.

Another nice addition would be for the game to save the last setup options and reload those when restarted as sometimes i forget to set the small cities check box.

---

**Comment by Hueristic** [comment]
Although your spin on this request does make sense and would be a welcome addition what you need to understand about my request is that me and my friends do not take the game all that seriously and just have fun so by allowing to add more tiles we can continue. Also we have had dead ties along the 100 - 15 area a few times with 4 players so that's kind of a drag after a very long game.

**Comment by Hueristic** [comment]
We seem to be hung up on the recommendation to add extra tiles to extend the game and missed the other feature request.

That was to allow more than one person to sit hotseat and also connect to lobby. Normally we run multiple instances from one system and that works but multiple users one one client is cleaner.

Also we have had connection issues and upon rejoining some how one instance suddenly had both players in one instance! So Obviously the code is there for this but maybe it's been removed for testing or some such thing?

**Comment by Hueristic** [comment]
I'm going to add the first request as a separate request and remove it from the OP.
