### ISSUE TITLE
Additional playing options

### ISSUE THREAD

**Issue by hkiel** [farin/JCloisterZone#266]
When I play with my kids we usually do not use all possible rules:

1. we do not put the farmers on the meadows (option "disable farmers")
2. we have the towers extension, but we only use the extra cards (have "extra cards only" tick for each extension?) an leave the towers unused

Maybe it would be possible to implement these options to the game/extensions?

**Comment by x-iso** [comment]
While at it, I would also suggest option to remove barns from Abbey and Mayor extension. Since barns can be easily exploited to score field points multiple times trough the game, it often breaks the normal game flow, so when I play with friends we just agree to never use it. For online matches it might be a hassle though, if anyone forgets about agreement.

**Comment by farin** [comment]
For now you can use workaround, 
- just select your favorite game config and save it as preset
- Then close game 
- manually edit config.yaml (file location should be displayed in about dialog, but it is in game dirr or in AppData in user dir or in ~/.JCloisterZone, depends on OS)
- find you preset in config and remove TowerCapability from list
- save it and run game again, you preset should be now game with toiwer tiles only without towers

@x-iso dtto same think is possible with barns, btw you can load preset and play through network with remote player even wtth this preset

**Comment by x-iso** [comment]
@farin I guess that works too, but it would be good to be able to check and uncheck those capabilities within extensions in UI.

**Comment by farin** [comment]
both is now possible in 5.x
