### ISSUE TITLE
UPNP support

### ISSUE THREAD

**Issue by masaykh** [farin/JCloisterZone#57]
Please add upnp support using
this http://4thline.org/projects/cling/
or this https://code.google.com/p/weupnp/
or this http://sourceforge.net/projects/cgupnpjava/
or in any other available way.

**Comment by farin** [comment]
@masaykh what should be good for?

**Comment by joelpurra** [comment]
@farin: because most users don't know how to configure their own home routers and open TCP ports. I have problems too, because I don't have the passwords to my friends' routers when hosting from their homes. This technical problem limits the number of people who can host normal multiplayer games. As there are already UPNP libraries for java available, implementation should not be hard in JCZ.

**Comment by farin** [comment]
3.1 has play online feature, which should solve this  satisfactorily.
