### ISSUE TITLE
Consider semantic versioning for version 3.1.0

### ISSUE THREAD

**Issue by joelpurra** [farin/JCloisterZone#84]
In order to get an understanding of how much a release of JCZ has changed from the previous one, I propose using the [semantic versioning standard, semver](http://semver.org/):

---

## Semver summary

Given a version number MAJOR.MINOR.PATCH, increment the:

1. MAJOR version when you make incompatible API changes,
1. MINOR version when you add functionality in a backwards-compatible manner, and
1. PATCH version when you make backwards-compatible bug fixes.

Additional labels for pre-release and build metadata are available as extensions to the MAJOR.MINOR.PATCH format.

---

@farin: I think this pretty much follows the current style - like `3.0.2` - it's just formalized. The reason I thought of is that I think the next version might be tagged `3.1`, while semver proposes to always use three numbers as in `3.1.0` so it's consistent.

**Comment by farin** [comment]
There are two different things, 3 number  version and it's semantic meaning. (because semver is mainly about libraries and versions should reflect api changes - breaking/unbreaking ... )

While semver is good for automatic processing, like dependencies, and developer friendly I am not convinced if it's ideal for end products and broad user audience. See firefox using primary 2 number version.

**Comment by joelpurra** [comment]
> There are two different things, 3 number version and it's semantic meaning. (because semver is mainly about libraries and versions should reflect api changes - breaking/unbreaking ... )

Yes, libraries and packages have stricter demands on semantic version numbers. This does not mean that the same ruleset of breaking changes, improvements and fixes isn's useful for humans. Suggesting the same scheme for a customer products also makes sense, as it formalizes for example when config and save files are incompatible.
 
> While semver is good for automatic processing, like dependencies, and developer friendly I am not convinced if it's ideal for end products and broad user audience. See firefox using primary 2 number version.

Yes, they are using marketing numbers in order to *compete* with Chrome and Internet Explorer. This is different - I don't see JCZ competing with another game by incrementing the version number the fastest.

> [Firefox is released on a six week schedule, meaning that every sixth week there will be new versions of Firefox Release.](https://wiki.mozilla.org/Release_Management/Release_Process)

**Comment by joelpurra** [comment]
I see you went with four digits instead of two, and a two digit "name" with a beta label ;)

https://github.com/farin/JCloisterZone/commit/cacd3daac2bd4f6481705abc171b3481561e750d#diff-77bfdc3635aac88a4e49e6cfa506146eL17

**Comment by farin** [comment]
@joelpurra this only internal string with protocol revision. I avoid integer number (i don't know if it's incremented or not) This string simply express if app is compatible on protocol and engine layer. I derived it from app version (sometimes app version is increased but protocol not) And now I need increase version to deny alpha builds connect to online server (because of protocol change)   

In fact there can be sring in protocol number. so i can choose any other.
