### ISSUE TITLE
Add Dutch and Belgium Monasteries

### ISSUE THREAD

**Issue by Cu8eR** [farin/JCloisterZone#90]
Add Dutch and Belgium Monasteries

It should not be difficult to add these 6 tiles.

**Comment by farin** [comment]
@Cu8eR it think about it but I am still not sure it's is just only different graphical skin.
Because in fact it is, tile are same. So it could be achieved by graphics plugin (only disadvantage is you can't play both together) 
Next think after comming relase will be change in game setup. You should be able add tiles from one expansion multiple times - and with this it's make even more less sense to add this as separate expansion - want to be in 3.2 - (but still you mus choose one graphics theme - seems to be only minor issue for me)

**Comment by Cu8eR** [comment]
I can provide you original tiles - just tell me

**Comment by farin** [comment]
@Cu8eR please, at least i will pack it as theme and add to 3.1

**Comment by Cu8eR** [comment]
@farin - check your email for more info

**Comment by rawling** [comment]
These expansions aren't just a replacement set of graphics for 6 tiles, they also add a new way of playing a follower on those 6 tiles.

**Comment by farin** [comment]
implemented as theme in 3.4.1
