### ISSUE TITLE
feature: add (optional) player-turn countdown timer / chess timer mechanism

### ISSUE THREAD

**Issue by fatsu** [farin/JCloisterZone#96]
We usually play a game with JCloisterzone between colleagues during lunch break. But as some of these colleagues take a lot of time to think over their options/move, the lunch break tends to become too long.

It would be nice to have an optional customizable X second countdown timer per player-turn. This would limit the total time a game would take.

Possible actions when timer hits zero: 
- discard tile and switch to next player
- remove penalty points every Y seconds

**Comment by joelpurra** [comment]
> It would be nice to have an optional customizable X second countdown timer per player-turn. This would limit the total time a game would take.

Have discussed the same problem with my game buddies. Love the solution.

We've also discussed having a [chess timer](https://en.wikipedia.org/wiki/Game_clock), which would limit the *total time* of all your turns. If you take more than Y minutes total, you automatically lose the game! There are [other time control options](https://en.wikipedia.org/wiki/Time_control), such as adding time delay of a few seconds when you start your move so that if you make a fast move you can gain some time.

**Comment by farin** [comment]
Chess timer is in my task queue - it's easiest solution then turn timer because there is no doubt how handle depleted time. 
For turn timer discard is not option (sometimes you want to discard a tile but you can't)

**Comment by fatsu** [comment]
Good. A chess-timer mechanism would probably do the trick as well.

In addition: I guess some sort of time-management solution will be required in online play as well. You always have those guys that start slow-playing or stop playing once they are sure to have lost in order to force or trick the winner to abandon or stop the game and prevent ranking to get applied.

**Comment by Cu8eR** [comment]
I agree - this is a must have feature for online multiplayer over jcloisterzone public server
